### ISSUE TITLE
Does --max-size matter on low memory systems?

### ISSUE THREAD

**Issue by eh8** [maximumadmin/zramd#8]
By default, `zramd` will allocate a maximum of eight gigabytes for swap. On systems such as the RPI, this is significantly higher than the actual amount of memory installed by the manufacturer. Do you recommend adjusting this parameter to cater to low memory systems, or does the default configuration simply work as well?

**Comment by maximumadmin** [comment]
The default configuration will work just fine on the Raspberry Pi, `--max-size` defines the maximum amount of memory that `--fraction` is allowed to use (`--fraction` can be `1.0` at most) so you will never get a swap larger than the actual amount of physical memory.

e.g.
```
root# free -h
              total        used        free      shared  buff/cache   available                              
Mem:          974Mi       126Mi       342Mi        81Mi       506Mi       706Mi                              
Swap:            0B          0B          0B                                                                  

root# zramd start --max-size 32000                                                 
root# free -h                                                                      
              total        used        free      shared  buff/cache   available                              
Mem:          974Mi       134Mi       333Mi        81Mi       506Mi       697Mi                              
Swap:         974Mi          0B       974Mi 
```
